### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by devxpy** [githubsaturn/captainduckduck#192]
I just installed captainduckduck and i get this error while trying to set it up for the first time
```
root~#  captainduckduck serversetup
/usr/local/lib/node_modules/captainduckduck/captainduckduck-serversetup.js:34
    let machines = configs.get('captainMachines');
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

- Ubuntu 16.10 (digital ocean)
- RAM 1GB
- Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz

```
root~# node --version
v4.2.6
```
```
root~# docker --version
Docker version 17.12.0-ce, build c97c6d6
```
```
root~# captainduckduck --version
1.0.12
```
```
root~# npm --version
3.5.2
```

**Comment by githubsaturn** [comment]
You're using a really old version of Node v4, update your local Node and things will work.

**Comment by githubsaturn** [comment]
https://nodejs.org/en/

![image](https://user-images.githubusercontent.com/10582082/36552152-077c946a-17ae-11e8-94e4-c3f4b4adde10.png)

**Comment by devxpy** [comment]
Thanks, 

```
root~# node --version
v8.9.4
```
It runs fine now, but i am getting this error.

```
root~# captainduckduck serversetup 
 
Setup your Captain server
 
? Have you already installed Captain on your server by running the following line:
mkdir /captain && docker run -v /var/run/docker.sock:/var/run/docker.sock dockersaturn/captainduckduck ? Yes
✔ Login...
? Enter IP address of your captain server: -------------
? Enter a root domain for this Captain server. For example, enter test.yourdomain.com if you setup your DNS to point *.test.yourdomain
✖ Changing Domain...

Error: 1107
Error: Verification Failed.
```

I have tested using mxtoolbox.com and my domain points to the correct location `cbt.baluniclasseshaldwani.com`

**Comment by devxpy** [comment]
From my domain settings.
![image](https://user-images.githubusercontent.com/19492893/36559479-2ae8444a-1834-11e8-95c5-b88812366f72.png)

**Comment by githubsaturn** [comment]
You need to user a wildcard entry.

`*.something.yourdomain.com` and NOT `something.yourdomain.com`
It's documented here:
https://github.com/githubsaturn/captainduckduck/wiki/Getting-Started#step-2-connect-root-domain

**Comment by devxpy** [comment]
i tried doing that,

![image](https://user-images.githubusercontent.com/19492893/36560025-a43c95a2-1835-11e8-8c95-96e7a61470f0.png)

**Comment by githubsaturn** [comment]
https://www.digitalocean.com/community/tutorials/how-to-set-up-and-test-dns-subdomains-with-digitalocean-s-dns-panel

**Comment by devxpy** [comment]
Thank you for the wonderful support, 
I have this error now, i have a django / postgres app
```
root# captainduckduck deploy
 
 
Preparing deployment to Captain...
 
? Select the Captain Machine you want to deploy to: exams-captain-machine at https://captain.almightydev.com
? Enter the "git" branch you would like to deploy: ugly
? Enter the Captain app name this directory will be deployed to:  exams-captain-app
? Note that uncommitted files and files in gitignore (if any) will not be pushed to server. Please confirm so that deployment process 
can start. Yes
 
 
Deploying to exams-captain-machine
 
Saving tar file to:
/home/django/exams/temporary-captain-to-deploy.tar
 
Pushing last commit on ugly: c66cba69feb5ce9e0c1d9b73ee0712fa983d20e8
Uploading file to https://captain.almightydev.com
 
This might take several minutes. PLEASE BE PATIENT...

Something bad happened. Cannot deploy " exams-captain-app"

{
  "statusCode": 502,
  "body": "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.13.9</center>\r\n</body>\r\n</html>\r\n",                                                                  
  "headers": {
    "server": "nginx/1.13.9",
    "date": "Fri, 23 Feb 2018 19:58:29 GMT",
    "content-type": "text/html",
    "content-length": "173",
    "connection": "close"
  },
  "request": {
    "uri": {
      "protocol": "https:",
      "slashes": true,
      "auth": null,
      "host": "captain.almightydev.com",
      "port": 443,
      "hostname": "captain.almightydev.com",
      "hash": null,
      "search": "?detached=1",
      "query": "detached=1",
      "pathname": "/api/v1/user/appData/%20exams-captain-app/",
      "path": "/api/v1/user/appData/%20exams-captain-app/?detached=1",
      "href": "https://captain.almightydev.com/api/v1/user/appData/%20exams-captain-app/?detached=1"
    },
    "method": "POST",
    "headers": {
      "x-namespace": "captain",
      "x-captain-auth": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7Im5hbWVzcGFjZSI6ImNhcHRhaW4iLCJ0b2tlblZlcnNpb24iOiJlZTJiOTZkMC04ZDJkLTQ5ZTctYmZjNC02YzJlODA0MzU5ZjMifSwiaWF0IjoxNTE5NDE1Nzk2LCJleHAiOjE1NTU0MTU3OTZ9.7FRMA4LUK0oymvRP4zdPRb8M7uvBmSI7bRKXlfpAVNk",
      "content-type": "multipart/form-data; boundary=--------------------------953808072105674543419823",
      "content-length": 3584388
    }
  }
}

```

**Comment by githubsaturn** [comment]
I deleted your post as it had your auth token in it! When you are posting logs make sure it doesn't include security information.

**Comment by githubsaturn** [comment]
The error that you posted could have been a temporary error if you just restarted your server. Retry again to see if you get that error.

If you still get that error, let me know.

**Comment by devxpy** [comment]
Thanks, that error seems to be resolved now. Thanks for deleting that comment.

I get this error now. It can't seem to install postgres. 
```
root# captainduckduck deploy
 
 
Preparing deployment to Captain...
 
? Select the Captain Machine you want to deploy to: exams_captain_machine at https://captain.almightydev.com
? Enter the "git" branch you would like to deploy: ugly
? Enter the Captain app name this directory will be deployed to: exams-captain-app
? Note that uncommitted files and files in gitignore (if any) will not be pushed to server. Please confirm so that deployment process 
can start. Yes
 
 
Deploying to exams_captain_machine
 
Saving tar file to:
/home/django/exams/temporary-captain-to-deploy.tar
 
Pushing last commit on ugly: *********************************
Uploading file to https://captain.almightydev.com
 
This might take several minutes. PLEASE BE PATIENT...
Building started: exams-captain-app
 
------------------------- Sat Feb 24 2018 09:17:36 GMT+0000 (UTC)
Build started for exams-captain-app
Step 1/8 : FROM library/python:3.6.1-alpine3.6

---> *********************************
Step 2/8 : RUN mkdir -p /usr/src/app

---> Using cache
---> *********************************
Step 3/8 : WORKDIR /usr/src/app

---> Using cache
---> *********************************
Step 4/8 : COPY ./src/requirements.txt /usr/src/app/

---> Using cache
---> *********************************
Step 5/8 : RUN pip install --no-cache-dir -r requirements.txt

---> Running in *********************************
Collecting Babel==2.5.3 (from -r requirements.txt (line 1))
.
.
.
.
Collecting psycopg2==2.7.3.2 (from -r requirements.txt (line 21))
Downloading psycopg2-2.7.3.2.tar.gz (425kB)
Complete output from command python setup.py egg_info:
running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    Error: pg_config executable not found.
    
    Please add the directory containing pg_config to the PATH
    or specify the full executable path with the option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-btime05h/psycopg2/

{"code":1,"message":"The command '/bin/sh -c pip install --no-cache-dir -r requirements.txt' returned a non-zero code: 1"}
The command '/bin/sh -c pip install --no-cache-dir -r requirements.txt' returned a non-zero code: 1
----------------------
Deploy failed!
Error: {"code":1,"message":"The command '/bin/sh -c pip install --no-cache-dir -r requirements.txt' returned a non-zero code: 1"}
The command '/bin/sh -c pip install --no-cache-dir -r requirements.txt' returned a non-zero code: 1
 

Something bad happened. Cannot deploy "exams-captain-app"
```

**Comment by githubsaturn** [comment]
This error is specific to your application. I won't be able to pinpoint the issue, but I can help you to the right direction.

From the look of it, I think your application structure is unusual. Can you tell me more about your application structure? Do you expect to install postgres as part of your requirement.txt? You should be using a postgres address, and install postgres separately.

**Comment by githubsaturn** [comment]
Try this as your captain-definition file:
```
{
  "schemaVersion": 1,
  "dockerfileLines": [
    "FROM library/python:3.6.4-jessie",
    "RUN mkdir -p /usr/src/app",
    "WORKDIR /usr/src/app",
    "COPY ./src/requirements.txt /usr/src/app/",
    "RUN pip install --no-cache-dir -r requirements.txt",
    "COPY ./src /usr/src/app",
    "EXPOSE 80",
    "CMD [\"python\", \"manage.py\", \"runserver\", \"0.0.0.0:80\"]"
  ]
}
```

**Comment by devxpy** [comment]
```
Babel==2.5.3
certifi==2017.11.5
chardet==3.0.4
defusedxml==0.5.0
dj-database-url==0.4.2
Django==2.0.2
django-allauth==0.34.0
django-debug-toolbar==1.9.1
django-extensions==1.9.9
django-multiselectfield==0.1.8
django-phonenumber-field==2.0.0
django-rest-framework==0.1.0
django-widget-tweaks==1.4.1
djangorestframework==3.7.7
httplib2==0.10.3
idna==2.6
oauth2==1.9.0.post1
oauthlib==2.0.6
phonenumberslite==8.8.9
Pillow==5.0.0
psycopg2==2.7.3.2
PyJWT==1.5.3
python-dateutil==2.6.1
python-google-places==1.4.1
python-openid==2.2.5
python3-openid==3.1.0
pytz==2018.3
requests==2.18.4
requests-oauthlib==0.8.0
six==1.11.0
sqlparse==0.2.4
tinydb==3.7.0
typing==3.6.2
ujson==1.35
urllib3==1.22
Werkzeug==0.14.1
whitenoise==3.3.1

```

**Comment by devxpy** [comment]
Django requires postgres's python driver to be installed. I don't really have a choice in installing `psycopg2` module.

**Comment by githubsaturn** [comment]
Did you try the captain-definition file that i posted above?

**Comment by devxpy** [comment]
doing it

**Comment by devxpy** [comment]
It works fine now!
 
```
Deployed successful: exams-captain-app
App is available at https://exams-captain-app.almightydev.com
```
 i get a 502 bad gateway nginx tho

**Comment by githubsaturn** [comment]
https://github.com/githubsaturn/captainduckduck/wiki/Troubleshooting#successful-deploy-but-502-bad-gateway-error

**Comment by devxpy** [comment]
I am sorry to bother you so much, i am a noob in deployment area.

`docker service logs srv-captain--my-app --since 60m --follow`
returns Nothing for my app. I made a postgreql app and it seems to run fine. But the python app's logs are empty.

**Comment by githubsaturn** [comment]
A couple of handy lines:
- Run `docker service ls` if you see `1/1` it means your application is running if you see `0/1` it means your application is not running
- Run `docker service update --detach --force srv-captain--yourappname` to restart your app
- Run `docker service logs srv-captain--yourappname --since 60m --follow` to see logs

If you don't see logs it means your application exits before even starting! To troubleshoot, have a SSH session with `docker service logs srv-captain--yourappname --since 60m --follow` to view your application, then open up another SSH session and restart your app. Hopefully, it'll show you some logs.

**Comment by devxpy** [comment]
Thanks, i'll look around!

**Comment by devxpy** [comment]
I tried that, and I still get an empty service log.

Anyways, i have a bit of doubt regarding docker-machine.

I was learning docker using the tutorials.
You say [here](https://github.com/githubsaturn/captainduckduck/issues/11) that captain uses swarm for managing instances, as opposed to a compose file. 
The [tutorials](https://github.com/docker/labs/blob/master/swarm-mode/beginner-tutorial/README.md#preparation) on docker swarm say that you need to have docker-machine installed but i don't see docker-machine installed on my server. 

Where am i going wrong?

**Comment by devxpy** [comment]
Also, i tried running the interactive tty using  `docker run -it img-captain--exams-captain-app:latest`.

It shows the following error.

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f106dac3158>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python3.6/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 327, in execute
    autoreload.check_errors(django.setup)()
  File "/usr/local/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/src/app/Users/models.py", line 2, in <module>
    from django.contrib.auth.models import AbstractUser, BaseUserManager
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 114, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 315, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/options.py", line 205, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/usr/local/lib/python3.6/site-packages/django/db/__init__.py", line 33, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 202, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 110, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/db/backends/postgis/base.py", line 6, in <module>
    from .features import DatabaseFeatures
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/db/backends/postgis/features.py", line 1, in <module>
    from django.contrib.gis.db.backends.base.features import BaseSpatialFeatures
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/db/backends/base/features.py", line 3, in <module>
    from django.contrib.gis.db.models import aggregates
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/db/models/__init__.py", line 3, in <module>
    import django.contrib.gis.db.models.functions  # NOQA
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/db/models/functions.py", line 3, in <module>
    from django.contrib.gis.db.models.fields import BaseSpatialField, GeometryField
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/db/models/fields.py", line 3, in <module>
    from django.contrib.gis import forms, gdal
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/forms/__init__.py", line 3, in <module>
    from .fields import (  # NOQA
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/forms/fields.py", line 2, in <module>
    from django.contrib.gis.geos import GEOSException, GEOSGeometry
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/geos/__init__.py", line 5, in <module>
    from .collections import (  # NOQA
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/geos/collections.py", line 9, in <module>
    from django.contrib.gis.geos.geometry import GEOSGeometry, LinearGeometryMixin
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/geos/geometry.py", line 8, in <module>
    from django.contrib.gis import gdal
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/gdal/__init__.py", line 28, in <module>
    from django.contrib.gis.gdal.datasource import DataSource
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/gdal/datasource.py", line 39, in <module>
    from django.contrib.gis.gdal.driver import Driver
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/gdal/driver.py", line 5, in <module>
    from django.contrib.gis.gdal.prototypes import ds as vcapi, raster as rcapi
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/gdal/prototypes/ds.py", line 9, in <module>
    from django.contrib.gis.gdal.libgdal import GDAL_VERSION, lgdal
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/gdal/libgdal.py", line 43, in <module>
    % '", "'.join(lib_names)
django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tried "gdal", "GDAL", "gdal2.2.0", "gdal2.1.0", "gdal2.0.0", "gdal1.11.0", "gdal1.10.0", "gdal1.9.0"). Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.
/django/contrib/gis/gdal/libgdal.py", line 43, in <module>
    % '", "'.join(lib_names)

```

**Comment by devxpy** [comment]
So apparently you have to run it in tty mode to see the logs. More [here](https://stackoverflow.com/questions/42995277/django-in-docker-cant-see-logs) 

I need to have that module installed in my dockerfile lines i guess..

**Comment by devxpy** [comment]
any idea how to solve this?

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f59cd104f28>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python3.6/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 327, in execute
    autoreload.check_errors(django.setup)()
  File "/usr/local/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/src/app/Users/models.py", line 2, in <module>
    from django.contrib.auth.models import AbstractUser, BaseUserManager
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 114, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 315, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/options.py", line 205, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/usr/local/lib/python3.6/site-packages/django/db/__init__.py", line 33, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 202, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 110, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/db/backends/postgis/base.py", line 6, in <module>
    from .features import DatabaseFeatures
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/db/backends/postgis/features.py", line 1, in <module>
    from django.contrib.gis.db.backends.base.features import BaseSpatialFeatures
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/db/backends/base/features.py", line 3, in <module>
    from django.contrib.gis.db.models import aggregates
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/db/models/__init__.py", line 3, in <module>
    import django.contrib.gis.db.models.functions  # NOQA
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/db/models/functions.py", line 3, in <module>
    from django.contrib.gis.db.models.fields import BaseSpatialField, GeometryField
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/db/models/fields.py", line 3, in <module>
    from django.contrib.gis import forms, gdal
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/forms/__init__.py", line 3, in <module>
    from .fields import (  # NOQA
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/forms/fields.py", line 2, in <module>
    from django.contrib.gis.geos import GEOSException, GEOSGeometry
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/geos/__init__.py", line 5, in <module>
    from .collections import (  # NOQA
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/geos/collections.py", line 9, in <module>
    from django.contrib.gis.geos.geometry import GEOSGeometry, LinearGeometryMixin
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/geos/geometry.py", line 8, in <module>
    from django.contrib.gis import gdal
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/gdal/__init__.py", line 28, in <module>
    from django.contrib.gis.gdal.datasource import DataSource
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/gdal/datasource.py", line 39, in <module>
    from django.contrib.gis.gdal.driver import Driver
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/gdal/driver.py", line 5, in <module>
    from django.contrib.gis.gdal.prototypes import ds as vcapi, raster as rcapi
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/gdal/prototypes/ds.py", line 9, in <module>
    from django.contrib.gis.gdal.libgdal import GDAL_VERSION, lgdal
  File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/gdal/libgdal.py", line 43, in <module>
    % '", "'.join(lib_names)
django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tried "gdal", "GDAL", "gdal2.2.0", "gdal2.1.0", "gdal2.0.0", "gdal1.11.0", "gdal1.10.0", "gdal1.9.0"). Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.
```

**Comment by githubsaturn** [comment]
Change your captain-definition file to
```{
  "schemaVersion": 1,
  "dockerfileLines": [
    "FROM library/python:3.6.4-jessie",
    "RUN apt-get update && apt-get install -y binutils libproj-dev gdal-bin",
    "RUN mkdir -p /usr/src/app",
    "WORKDIR /usr/src/app",
    "COPY ./src/requirements.txt /usr/src/app/",
    "RUN pip install --no-cache-dir -r requirements.txt",
    "COPY ./src /usr/src/app",
    "EXPOSE 80",
    "CMD [\"python\", \"manage.py\", \"runserver\", \"0.0.0.0:80\"]"
  ]
}

```

**Comment by devxpy** [comment]
Yeah, I tried that, but the python image doesn't contain gdal-bin.
I tried to build python on this image but that doesn't seem to work 
https://googleweblight.com/i?u=https://hub.docker.com/r/geodata/gdal/~/dockerfile/&hl=en-IN&grqid=ZElL5OXG

**Comment by githubsaturn** [comment]
Try this one:

```
  "schemaVersion": 1,
  "dockerfileLines": [
    "FROM library/python:3.6.4-jessie",
    "RUN apt-get update && apt-get install -y binutils libproj-dev gdal-bin",
    "RUN mkdir -p /usr/src/app",
    "WORKDIR /usr/src/app",
    "COPY ./src/requirements.txt /usr/src/app/",
    "RUN pip install --no-cache-dir -r requirements.txt",
    "COPY ./src /usr/src/app",
    "ENV GDAL_LIBRARY_PATH /usr/lib/ogdi/libgdal.so"
    "EXPOSE 80",
    "CMD [\"python\", \"manage.py\", \"runserver\", \"0.0.0.0:80\"]"
  ]
}
```
Added environmental variable line from https://stackoverflow.com/questions/21513980/attributeerror-usr-lib-ogdi-libgdal-so-undefined-symbol-gdalversioninfo

**Comment by devxpy** [comment]
Alright, got the server up and running!
Where do i get the postgresql database ip and port?

i tried setting the port mapping like so 
![image](https://user-images.githubusercontent.com/19492893/36656996-bf3f214a-1af0-11e8-9a14-8a6e3779678d.png)

but the command `docker port srv-captain--exams-postgresql-app.1.*****`
returns nothing.

```
psycopg2.OperationalError: could not connect to server: Connection refused
        Is the server running on host "127.0.0.1" and accepting
        TCP/IP connections on port 5432?
```

**Comment by githubsaturn** [comment]
You don't need port mapping. Simply use
- host: `srv-captain--exams-postgresql-app`
- port: `5432`
https://github.com/githubsaturn/captainduckduck/wiki/Complete-Webapp-Tutorial

Port mapping is used if you want to connect to your Postgres from your laptop. It ports the postgres container port to the server port.

**Comment by devxpy** [comment]
```
psycopg2.OperationalError: could not translate host name "srv-captain--exams-postgresql-app" to address: Name or service not known
```

I tried using `tcp://srv-captain--exams-postgresql-app`

```
psycopg2.OperationalError: could not translate host name "tcp://srv-captain--exams-postgresql-app" to address: Name or service not known
```

**Comment by devxpy** [comment]
Thank you so much, my app is finally deployed!

How exactly do i go about performing database operations now?
I can't access `psql` from `docker run -it img-captain--postgresql:latest /bin/sh`

```
# psql
psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

**Comment by devxpy** [comment]
while performing `python manage.py migrate`, i get this error
```
psycopg2.OperationalError: could not open extension control file "/usr/share/postgresql/10/extension/postgis.control": No such file or directory
```

**Comment by githubsaturn** [comment]
This is NOT how you should do it!

> root#docker exec -it srv-captain--postgresql.1.a4990c3ln6j0o6nz7f2cmfuf3 bash
> # apt update
> # apt install postgis

This way, by every restart, you'll lose `postgis` package! Either do port mapping and connect to the database port from your local machine. Or if you really need `postgis` package, you should include that in Dockerfile and re-deploy your database container. To do this.
1. Create a captain-definition file with the following content
```
  "schemaVersion": 1,
  "dockerfileLines": [
    "FROM postgres:latest",
    "RUN apt-get update && apt-get install -y postgis"
  ]
}
```
2. Convert this file into a `tar` file
3. Open Captain dashboard
4. Go to your database app details page
5. Upload this file and "Deploy"

**Comment by devxpy** [comment]
Oh snap! will do that.
Here's a link to the app btw, if you want to have a look.
http://django.almightydev.com
