### ISSUE TITLE
How to handle dabase migrations in django?

### ISSUE THREAD

**Issue by devxpy** [githubsaturn/captainduckduck#200]
machine: docker 1GB

when i try `manage.py migrations` (after a successful makemigrations) in my already deployed `captain-definition`, i get this error, 

Probably because migrations are not synced in my git repo and django cant detect which migrations are already applied to the database without the `migrations` folder

```
System check identified some issues:

WARNINGS:
Users.CustomUser: (auth.W004) 'CustomUser.phone_number' is named as the 'USERNAME_FIELD', but it is not unique.
        HINT: Ensure that your authentication backend(s) can handle non-unique usernames.
Operations to perform:
  Apply all migrations: Exams, Users, account, admin, auth, contenttypes, sessions, sites, socialaccount
Running migrations:
  Applying Exams.0002_auto_20180309_1911...Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: column "owner_id" of relation "Exams_topic" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/migration.py", line 122, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/operations/fields.py", line 84, in database_forwards
    field,
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 421, in add_field
    self.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 117, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "owner_id" of relation "Exams_topic" already exists

```

**Comment by githubsaturn** [comment]
Please share your captain-definition file content. I personally don't know much about Django migrations. But I believe if you share your captain-definition file content, someone else would be able to help

**Comment by devxpy** [comment]
captian-definition 

```{
  "schemaVersion": 1,
  "dockerfileLines": [
    "FROM library/python:3.6.4-jessie",

    "RUN apt-get update && apt-get install -y binutils libproj-dev gdal-bin",
    "RUN mkdir -p /usr/src/app",
    "WORKDIR /usr/src/app",

    "RUN pip install pipenv --upgrade",
    "COPY ./src /usr/src/app",
    "RUN pipenv install --deploy --system",

    "EXPOSE 80",
    "COPY ./src/runserver.sh /usr/local/bin/",
    "CMD [\"sh\", \"runserver.sh\"]"
  ]
}
```
entrypoint.sh
```
#!/bin/sh

python manage.py collectstatic --noinput
python manage.py makemigrations
python mange.py migrate
gunicorn quiz.wsgi --bind=0.0.0.0:80
```

**Comment by devxpy** [comment]
I have posted a question on stackoverflow as you advised. I couldnt get the `captainduckduck` tag though, since that tag is not created by someone previously and it requires 1500 rep to create new tags

**Comment by githubsaturn** [comment]
CaptainDuckDuck uses docker under the hood. So just tagging with Docker should be enough. 

Keep in mind that captain-definition is called Dockerfile in Docker terms.

**Comment by devxpy** [comment]
I am thinking to make a django one click app, to avoid the common traps and problems while using django.

**Comment by githubsaturn** [comment]
> I am thinking to make a django one click app, to avoid the common traps and problems while using django.

One click apps are apps with pre-baked source code. You cannot create a one-click app for a generic "PHP" or "Django" app. One click apps contain the entire docker image.


As for your problem, I feel like there is a typo in your captain-definition. In your definition you are copying the "runserver.sh" file into the container, but all your migration code is in `entrypoint.sh` file which is not copied to your image.

**Comment by devxpy** [comment]
That was a typo on GitHub, sorry

**Comment by devxpy** [comment]
Someone on stackoverflow has suggested that i add the migrations folder to git. 

I will try that and get back to you.

**Comment by devxpy** [comment]
For reference, this is solved here.
https://stackoverflow.com/a/49426100/7061265
