### ISSUE TITLE
Installation fail - must specify a listening address

### ISSUE THREAD

**Issue by vincelwt** [githubsaturn/captainduckduck#270]
Hi, during installation, I have the following error:
My server is a baremetal C2M on Scaleway, with firewall disabled.

It has a private IP and a public one. The one detected is the public one

```
root@myserver:~# docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock dockersaturn/captainduckduck
npm info it worked if it ends with ok
npm info using npm@5.4.2
npm info using node@v8.7.0
npm info lifecycle captain-duckduck@0.0.0~prestart: captain-duckduck@0.0.0
npm info lifecycle captain-duckduck@0.0.0~start: captain-duckduck@0.0.0

> captain-duckduck@0.0.0 start /usr/src/app
> node ./bin/www

Captain Starting ...
Installing Captain Service ...



 >>>> Checking System Compatibility <<<<
   Docker Version passed.
   Ubuntu detected.
   X86 CPU detected.
   Total RAM 16767 MB
September 5th 2018, 3:04:11.741 pm    Starting swarm at 12.34.567.8:2377
Installation failed.
{ Error: (HTTP code 400) bad parameter - must specify a listening address because the address to advertise is not recognized as a system address, and a system's IP address to use could not be uniquely identified
    at /usr/src/app/node_modules/docker-modem/lib/modem.js:254:17
    at getCause (/usr/src/app/node_modules/docker-modem/lib/modem.js:284:7)
    at Modem.buildPayload (/usr/src/app/node_modules/docker-modem/lib/modem.js:253:5)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:229:14)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1057:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  reason: 'bad parameter',
  statusCode: 400,
  json:
   { message: 'must specify a listening address because the address to advertise is not recognized as a system address, and a system\'s IP address to use could not be uniquely identified' } }
npm info lifecycle captain-duckduck@0.0.0~poststart: captain-duckduck@0.0.0
npm info ok
root@myserver:~#
```

I manually figured how to start a swarm by providing the private IP address with the '--advertise-addr' flag, but how can I pass this to Captainduckduck installer ?

Thanks!

**Comment by githubsaturn** [comment]
Try this:
```
docker run -e "MAIN_NODE_IP_ADDRESS=9.9.9.9" -v /var/run/docker.sock.............
```
Replace `9.9.9.9` with your IP address.

**Comment by vincelwt** [comment]
Thanks! That solved it indeed :) 

I probably missed it in the docs. If not that'd be great to have in case others run into the same issue

**Comment by LiquidITGuy** [comment]
thanks for the tips
got the same problem : 
```
Error: (HTTP code 400) bad parameter - must specify a listening address because the address to advertise is not recognized as a system address, and a system's IP address to use could not be uniquely identified
    at /usr/src/app/node_modules/docker-modem/lib/modem.js:301:17
    at getCause (/usr/src/app/node_modules/docker-modem/lib/modem.js:331:7)
    at Modem.buildPayload (/usr/src/app/node_modules/docker-modem/lib/modem.js:300:5)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:275:14)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  reason: 'bad parameter',
  statusCode: 400,
  json: {
    message: "must specify a listening address because the address to advertise is not recognized as a system address, and a system's IP address to use could not be uniquely identified"
  }
}
```

be careful if you install it on local network, the ip setted is not the public ip (in dns) but the local network ip
