### ISSUE TITLE
Unable to add new Node

### ISSUE THREAD

**Issue by formatically** [githubsaturn/captainduckduck#274]
What is the problem?
Every time I try to add a new node I get a SSH Connection Error.  

This is what is logged:
```
captain-captain.1.kyn3zwl86pcn@AuthRampPaas    | September 13th 2018, 5:01:59.722 pm    Error: All configured authentication methods failed
captain-captain.1.kyn3zwl86pcn@AuthRampPaas    | Error: All configured authentication methods failed
captain-captain.1.kyn3zwl86pcn@AuthRampPaas    |     at tryNextAuth (/usr/src/app/node_modules/ssh2/lib/client.js:380:17)
captain-captain.1.kyn3zwl86pcn@AuthRampPaas    |     at SSH2Stream.onUSERAUTH_FAILURE (/usr/src/app/node_modules/ssh2/lib/client.js:591:5)
captain-captain.1.kyn3zwl86pcn@AuthRampPaas    |     at emitTwo (events.js:125:13)
captain-captain.1.kyn3zwl86pcn@AuthRampPaas    |     at SSH2Stream.emit (events.js:213:7)
captain-captain.1.kyn3zwl86pcn@AuthRampPaas    | POST /api/v1/user/system/nodes/ 200 26.881 ms - 54
captain-captain.1.kyn3zwl86pcn@AuthRampPaas    |     at parsePacket (/usr/src/app/node_modules/ssh2-streams/lib/ssh.js:3929:10)
captain-captain.1.kyn3zwl86pcn@AuthRampPaas    |     at SSH2Stream._transform (/usr/src/app/node_modules/ssh2-streams/lib/ssh.js:669:13)
captain-captain.1.kyn3zwl86pcn@AuthRampPaas    |     at SSH2Stream.Transform._read (_stream_transform.js:186:10)
captain-captain.1.kyn3zwl86pcn@AuthRampPaas    |     at SSH2Stream._read (/usr/src/app/node_modules/ssh2-streams/lib/ssh.js:251:15)
captain-captain.1.kyn3zwl86pcn@AuthRampPaas    |     at SSH2Stream.Transform._write (_stream_transform.js:174:12)
captain-captain.1.kyn3zwl86pcn@AuthRampPaas    |     at doWrite (_stream_writable.js:387:12)
captain-captain.1.kyn3zwl86pcn@AuthRampPaas    | September 13th 2018, 5:01:59.727 pm    Error: SSH Connection error!!
captain-captain.1.kyn3zwl86pcn@AuthRampPaas    | Error: SSH Connection error!!
captain-captain.1.kyn3zwl86pcn@AuthRampPaas    |     at Object.createError (/usr/src/app/src/api/ApiStatusCodes.js:5:21)
captain-captain.1.kyn3zwl86pcn@AuthRampPaas    |     at Client.<anonymous> (/usr/src/app/src/user/CaptainManager.js:636:51)
captain-captain.1.kyn3zwl86pcn@AuthRampPaas    |     at emitOne (events.js:115:13)
captain-captain.1.kyn3zwl86pcn@AuthRampPaas    |     at Client.emit (events.js:210:7)
captain-captain.1.kyn3zwl86pcn@AuthRampPaas    |     at tryNextAuth (/usr/src/app/node_modules/ssh2/lib/client.js:382:12)
captain-captain.1.kyn3zwl86pcn@AuthRampPaas    |     at SSH2Stream.onUSERAUTH_FAILURE (/usr/src/app/node_modules/ssh2/lib/client.js:591:5)
captain-captain.1.kyn3zwl86pcn@AuthRampPaas    |     at emitTwo (events.js:125:13)
captain-captain.1.kyn3zwl86pcn@AuthRampPaas    |     at SSH2Stream.emit (events.js:213:7)
captain-captain.1.kyn3zwl86pcn@AuthRampPaas    |     at parsePacket (/usr/src/app/node_modules/ssh2-streams/lib/ssh.js:3929:10)
captain-captain.1.kyn3zwl86pcn@AuthRampPaas    |     at SSH2Stream._transform (/usr/src/app/node_modules/ssh2-streams/lib/ssh.js:669:13)
```

I do have ufw disabled on both servers.  

Has anybody seen this issue before?

Answers to the following questions where applicable:
- Your OS and version? Ubuntu 16.04 
- RAM? 1gb

**Comment by githubsaturn** [comment]
This is an expected error when you use a wrong private key. Check your second server is set up properly to work with the private key you have. Read the following to test your private key: https://www.cyberciti.biz/faq/force-ssh-client-to-use-given-private-key-identity-file/
