### ISSUE TITLE
Error: Cannot find module 'assert-plus'

### ISSUE THREAD

**Issue by PookMook** [githubsaturn/captainduckduck#3]
When trying to login for the first time:
```
~/Documents/git/PookMook.github.io$ captainduckduck login
module.js:487
    throw err;
    ^

Error: Cannot find module 'assert-plus'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/captainduckduck/node_modules/http-signature/lib/parser.js:3:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

fixed with npm install -g assert-plus, but this could be a dependency

**Comment by githubsaturn** [comment]
Can you please mention your system OS and your npm version? Also, did it happen immediately after login command or after entering some info?

**Comment by PookMook** [comment]
Straight after installing captainduckduck

```
~/Documents/git/PookMook.github.io$ sudo  npm install -g npm captainduckduck

/usr/local/bin/captainduckduck -> /usr/local/lib/node_modules/captainduckduck/captainduckduck.js
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
+ npm@5.5.1
+ captainduckduck@1.0.5
added 245 packages, removed 23 packages, updated 44 packages and moved 1 package in 10.445s
arthur@arthur-MS-7919:~/Documents/git/PookMook.github.io$ captainduckduck login

module.js:487
    throw err;
    ^

Error: Cannot find module 'assert-plus'
```
deploy also was missing assert-plus ofc

Using npm v5.5.1
```
PookMook.github.io$ npm version
{ npm: '5.5.1',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  node: '8.0.0',
  openssl: '1.0.2k',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.11.0',
  v8: '5.8.283.41',
  zlib: '1.2.11' }
```

**Comment by githubsaturn** [comment]
Are you running Windows, Mac or Linux?

**Comment by PookMook** [comment]
Linux Ubuntu 16.04 on the client side (14.04 on the docker virtual server, if that matter)

**Comment by githubsaturn** [comment]
I cannot repro the crash. Tried on Windows and Ubuntu and it works fine every time. I also did some googling, and seems like there is an npm one-off bug. See this for example: https://github.com/FredrikNoren/ungit/issues/253

I'll keep this issue open for a couple of days to see if other people report the same problem.
