### ISSUE TITLE
npm install && npm cache clean --force' returned a non-zero code: 1

### ISSUE THREAD

**Issue by dottodot** [githubsaturn/captainduckduck#32]
After my app has uploaded the build is failing with the following error

```
{
  "status": 1109,
  "description": "The command '/bin/sh -c npm install && npm cache clean --force' returned a non-zero code: 1"
}
```
At first I thought it was possibly a memory issue or cpu as the monitoring showed 100% cpu usage. However I've tried a server with 2 cpus and 4GB memory and it still happens. There's a bit more info in the server logs but not sure what else it can be as the same app deploys ok to my current server which is running flynn.
```
st    | December 12th 2017, 11:51:35.632 am    Error: Wrapped: The command '/bin/sh -c npm install && npm cache clean --force' returned a non-zero code: 1
captain-captain.1.3oewb2lym48v@duck-test    | Error: Wrapped: The command '/bin/sh -c npm install && npm cache clean --force' returned a non-zero code: 1
captain-captain.1.3oewb2lym48v@duck-test    |     at errorize (/usr/src/app/src/utils/Logger.js:10:16)
captain-captain.1.3oewb2lym48v@duck-test    |     at Object.e (/usr/src/app/src/utils/Logger.js:45:19)
captain-captain.1.3oewb2lym48v@duck-test    |     at IncomingMessage.<anonymous> (/usr/src/app/src/docker/DockerApi.js:207:36)
captain-captain.1.3oewb2lym48v@duck-test    |     at emitOne (events.js:115:13)
captain-captain.1.3oewb2lym48v@duck-test    |     at IncomingMessage.emit (events.js:210:7)
captain-captain.1.3oewb2lym48v@duck-test    |     at addChunk (_stream_readable.js:264:12)
captain-captain.1.3oewb2lym48v@duck-test    |     at readableAddChunk (_stream_readable.js:247:13)
captain-captain.1.3oewb2lym48v@duck-test    |     at IncomingMessage.Readable.push (_stream_readable.js:209:10)
captain-captain.1.3oewb2lym48v@duck-test    |     at HTTPParser.parserOnBody (_http_common.js:140:22)
captain-captain.1.3oewb2lym48v@duck-test    |     at Socket.socketOnData (_http_client.js:438:20)
captain-captain.1.3oewb2lym48v@duck-test    | December 12th 2017, 11:51:35.633 am    Error: Wrapped: {"code":1,"message":"The command '/bin/sh -c npm install && npm cache clean --force' returned a non-zero code: 1"}
captain-captain.1.3oewb2lym48v@duck-test    | Error: Wrapped: {"code":1,"message":"The command '/bin/sh -c npm install && npm cache clean --force' returned a non-zero code: 1"}
captain-captain.1.3oewb2lym48v@duck-test    |     at errorize (/usr/src/app/src/utils/Logger.js:10:16)
captain-captain.1.3oewb2lym48v@duck-test    |     at Object.e (/usr/src/app/src/utils/Logger.js:45:19)
captain-captain.1.3oewb2lym48v@duck-test    |     at IncomingMessage.<anonymous> (/usr/src/app/src/docker/DockerApi.js:208:36)
captain-captain.1.3oewb2lym48v@duck-test    |     at emitOne (events.js:115:13)
captain-captain.1.3oewb2lym48v@duck-test    |     at IncomingMessage.emit (events.js:210:7)
captain-captain.1.3oewb2lym48v@duck-test    |     at addChunk (_stream_readable.js:264:12)
captain-captain.1.3oewb2lym48v@duck-test    |     at readableAddChunk (_stream_readable.js:247:13)
captain-captain.1.3oewb2lym48v@duck-test    |     at IncomingMessage.Readable.push (_stream_readable.js:209:10)
captain-captain.1.3oewb2lym48v@duck-test    |     at HTTPParser.parserOnBody (_http_common.js:140:22)
captain-captain.1.3oewb2lym48v@duck-test    |     at Socket.socketOnData (_http_client.js:438:20)
captain-captain.1.3oewb2lym48v@duck-test    | December 12th 2017, 11:51:35.642 am    Error: The command '/bin/sh -c npm install && npm cache clean --force' returned a non-zero code: 1
captain-captain.1.3oewb2lym48v@duck-test    | Error: The command '/bin/sh -c npm install && npm cache clean --force' returned a non-zero code: 1
captain-captain.1.3oewb2lym48v@duck-test    |     at Object.createError (/usr/src/app/src/api/ApiStatusCodes.js:5:21)
captain-captain.1.3oewb2lym48v@duck-test    |     at /usr/src/app/src/user/ServiceManager.js:270:46
captain-captain.1.3oewb2lym48v@duck-test    |     at <anonymous>
captain-captain.1.3oewb2lym48v@duck-test    |     at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by githubsaturn** [comment]
Is your application public? Can you share the repo?

If it's private, can you please share the captain-definition file you're using for this project and some basic information about the project (whether it's a plain expressjs application or it's react or etc...)

**Comment by dottodot** [comment]
Unfortunately it's private but I'll share what I can.

This is my captain-definition
```
{
 "schemaVersion" :1 ,
 "templateId" :"node/8.9.3"
}
```
It's a Angular 5 app which is served from expressjs for server side rendering. Would the package.json be useful as well?

**Comment by githubsaturn** [comment]
Sure. `package.json` will be helpful. I'll try to repro it tonight.

Just to make sure, your project structure is something like this, right?
```
project-directory
     .git
     package.json
     captain-defintion
     OTHER_STUFF
```

**Comment by dottodot** [comment]
Yes my project structure looks correct

and my package.json is
```
{
  "name": "app-client",
  "version": "1.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "node server.js",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "engines": {
    "node": "8.x"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.1.0",
    "@angular/common": "^5.1.0",
    "@angular/compiler": "^5.1.0",
    "@angular/core": "^5.1.0",
    "@angular/forms": "^5.1.0",
    "@angular/http": "^5.1.0",
    "@angular/platform-browser": "^5.1.0",
    "@angular/platform-browser-dynamic": "^5.1.0",
    "@angular/platform-server": "^5.1.0",
    "@angular/router": "^5.1.0",
    "@angular/service-worker": "5.1.0",
    "@nguniversal/express-engine": "^5.0.0-beta.5",
    "@nguniversal/module-map-ngfactory-loader": "^5.0.0-beta.5",
    "angular-tinymce": "^3.1.4",
    "angular2-cookie-law": "^1.3.1",
    "angular2-toaster": "^4.0.1",
    "angulartics2": "^4.0.1",
    "bootstrap": "^4.0.0-beta.2",
    "cloudinary-core": "^2.3.0",
    "compression": "^1.7.1",
    "cookie-parser": "^1.4.3",
    "cookie-storage": "^3.0.0",
    "core-js": "^2.4.1",
    "dotenv": "^4.0.0",
    "express": "^4.15.3",
    "express-letsencrypt-simple": "^1.0.1",
    "express-minify-html": "^0.11.5",
    "express-redirect": "^1.2.2",
    "express-serve-static-core": "^0.1.1",
    "express-subdomain": "^1.0.5",
    "feathers": "^2.2.3",
    "feathers-authentication-client": "^0.3.1",
    "feathers-client": "^2.0.0",
    "feathers-hooks": "^2.1.2",
    "feathers-hooks-common": "^3.6.1",
    "feathers-reactive": "^0.5.4",
    "feathers-socketio": "^2.0.1",
    "flexboxgrid-sass": "^8.0.5",
    "flickity": "^2.0.10",
    "font-awesome": "^4.7.0",
    "forcedomain": "^0.8.1",
    "imagesloaded": "^4.1.3",
    "intersection-observer": "^0.4.3",
    "intl": "^1.2.5",
    "jsonwebtoken": "^8.0.1",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "ms": "^2.0.0",
    "ng-inline-svg": "^5.1.1",
    "ng2-charts": "^1.6.0",
    "ng2-daterangepicker": "^2.0.7",
    "ng2-dragula": "^1.5.0",
    "ng2-select": "^1.2.0",
    "ngx-auto-unsubscribe": "^2.1.0",
    "ngx-bootstrap": "^2.0.0-beta.9",
    "ngx-dropzone-wrapper": "^4.6.5",
    "ngx-json-ld": "^0.1.7",
    "ngx-slimscroll": "3.3.0",
    "normalize.css": "^7.0.0",
    "npm-run-all": "^4.0.2",
    "packery": "^2.1.1",
    "rollbar": "^2.3.1",
    "rxjs": "^5.5.5",
    "shrink-ray": "^0.1.3",
    "simple-line-icons": "^2.4.1",
    "socket.io-client": "^2.0.4",
    "tinymce": "^4.7.2",
    "web-animations-js": "^2.2.5",
    "zone.js": "^0.8.18"
  },
  "devDependencies": {
    "@angular/cli": "^1.6.0",
    "@angular/compiler-cli": "^5.1.0",
    "@angular/language-service": "^5.1.0",
    "@types/imagesloaded": "^4.1.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "@types/socket.io-client": "^1.4.31",
    "@types/uglify-js": "^2.6.29",
    "codelyzer": "^4.0.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-loader": "^3.1.1",
    "ts-node": "~3.2.0",
    "tslint": "^5.8.0",
    "typescript": "~2.4.2",
    "webpack-bundle-analyzer": "^2.8.2"
  }
}
```

**Comment by dottodot** [comment]
Actually let me do some more testing as I have an idea what it might be. I'd missed that in captain-definition you could add `dockerfileLines`  and in my previous attempts at starting to use docker I found that I needed to include the following in my Dockerfile for one of the npm packages.

```
RUN apk update \
    && apk upgrade \
    && apk add --no-cache --virtual .gyp \
    python \
    make \
    g++ \
```

**Comment by dottodot** [comment]
I have it working now I did need to have the custom build.
