### ISSUE TITLE
Infinite loop of "Auth token is not valid anymore" flash messages [web admin]

### ISSUE THREAD

**Issue by roelvan** [githubsaturn/captainduckduck#340]
What is the problem? After a fresh login I see many flash messages (infinite loop) after a few minutes of using the dashboard. See screenshot:
![12-30-2018-11 56 04](https://user-images.githubusercontent.com/2583837/50546655-9c7bd900-0c2b-11e9-8823-80ed3f1daa96.jpg)

Steps to reproduce the problem: login to the admin and open an app's settings page and wait a few minutes. When I inspect the network requests:
```
description: "Auth token is not valid anymore. Request for a new auth token"
status: 1106
```

Answers to the following questions where applicable:
- 1GB Ubuntu 16.04

**Comment by githubsaturn** [comment]
This not infinite loop. Logs/build status is being refreshed every 2 secs. When your auth token is expired you will see this error popup every two seconds as long as you are on the apps page. 

Now the question is what caused your auth token to expire. They have a very long life span. But they do get expire when the Captain service on the server restarts. You might have done an action that causes service to restart. Simply refresh the admin panel and login again. This issue should not be happening.

**Comment by roelvan** [comment]
@githubsaturn thanks for the quick reply. I already tried everything before posting this issue: from restarting captain duck duck to adding more ram to my Ubuntu instance. I logged out and logged in multiple times and I also removed all my cookies and local storage. But I'm still seeing these flash messages every 2 seconds.

**Comment by roelvan** [comment]
- Yes I see it every 2 seconds and also on other pages.
- Other pages also don't work when I see the flashes.
- Usually after a certain amount of time they appear. (a few minutes)

Generating a SSL certificate also doesn't work (even before the flashes appear).

Logs:
```
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | December 30th 2018, 8:28:43.230 pm    Error: Wrapped: Verification Failed for captain.cloud.thisisahiddendomainname.com
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | Error: Wrapped: Verification Failed for captain.cloud.thisisahiddendomainname.com
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at errorize (/usr/src/app/src/utils/Logger.js:10:16)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at Object.e (/usr/src/app/src/utils/Logger.js:45:19)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at Request._callback (/usr/src/app/src/user/CaptainManager.js:816:44)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at emitOne (events.js:115:13)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at Request.emit (events.js:210:7)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at Request.onRequestError (/usr/src/app/node_modules/request/request.js:881:8)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at emitOne (events.js:115:13)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at ClientRequest.emit (events.js:210:7)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at Socket.socketErrorListener (_http_client.js:385:9)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | December 30th 2018, 8:28:43.231 pm    Error: Wrapped: Error        Error: connect ETIMEDOUT 192.81.221.80:80
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | Error: Wrapped: Error        Error: connect ETIMEDOUT 192.81.221.80:80
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at errorize (/usr/src/app/src/utils/Logger.js:10:16)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at Object.e (/usr/src/app/src/utils/Logger.js:45:19)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at Request._callback (/usr/src/app/src/user/CaptainManager.js:817:44)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at emitOne (events.js:115:13)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at Request.emit (events.js:210:7)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at Request.onRequestError (/usr/src/app/node_modules/request/request.js:881:8)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at emitOne (events.js:115:13)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at ClientRequest.emit (events.js:210:7)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at Socket.socketErrorListener (_http_client.js:385:9)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | December 30th 2018, 8:28:43.232 pm    Error: Wrapped: body         undefined
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | Error: Wrapped: body         undefined
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at errorize (/usr/src/app/src/utils/Logger.js:10:16)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at Object.e (/usr/src/app/src/utils/Logger.js:45:19)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at Request._callback (/usr/src/app/src/user/CaptainManager.js:818:44)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at emitOne (events.js:115:13)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at Request.emit (events.js:210:7)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at Request.onRequestError (/usr/src/app/node_modules/request/request.js:881:8)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at emitOne (events.js:115:13)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at ClientRequest.emit (events.js:210:7)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at Socket.socketErrorListener (_http_client.js:385:9)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | December 30th 2018, 8:28:43.232 pm    Error: Wrapped: randomUuid   ea23efd7-ecc9-4f56-9053-ea8864a267d2
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | Error: Wrapped: randomUuid   ea23efd7-ecc9-4f56-9053-ea8864a267d2
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at errorize (/usr/src/app/src/utils/Logger.js:10:16)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at Object.e (/usr/src/app/src/utils/Logger.js:45:19)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at Request._callback (/usr/src/app/src/user/CaptainManager.js:819:44)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at emitOne (events.js:115:13)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at Request.emit (events.js:210:7)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at Request.onRequestError (/usr/src/app/node_modules/request/request.js:881:8)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at emitOne (events.js:115:13)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at ClientRequest.emit (events.js:210:7)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |     at Socket.socketErrorListener (_http_client.js:385:9)
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | GET /api/v1/user/appData/test-app-v1 304 1.165 ms - -
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | GET /api/v1/user/appData/test-app-v1 304 1.250 ms - -
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | GET /api/v1/user/appData/test-app-v1 304 4.205 ms - -
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | GET /api/v1/user/appData/test-app-v1 304 1.181 ms - -
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | GET /api/v1/user/appData/test-app-v1 304 1.311 ms - -
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | GET /api/v1/user/appData/test-app-v1 304 1.181 ms - -
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | GET /api/v1/user/appData/test-app-v1 304 1.791 ms - -
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | GET /api/v1/user/appData/test-app-v1 304 1.364 ms - -
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | GET /api/v1/user/appData/test-app-v1 304 2.149 ms - -
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | GET /api/v1/user/appData/test-app-v1 304 1.234 ms - -
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | GET /api/v1/user/appData/test-app-v1 304 1.133 ms - -
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | GET /api/v1/user/appData/test-app-v1 304 1.236 ms - -
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | December 30th 2018, 8:29:07.289 pm    Captain health check failed: #4 at captain.cloud.thisisahiddendomainname.com
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | December 30th 2018, 8:29:07.290 pm    NGINX health check failed: #4
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | npm info lifecycle captain-duckduck@0.0.0~start: Failed to exec start script
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | npm ERR! code ELIFECYCLE
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | npm ERR! errno 1
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | npm ERR! captain-duckduck@0.0.0 start: `node ./bin/www`
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | npm ERR! Exit status 1
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | npm ERR!
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | npm ERR! Failed at the captain-duckduck@0.0.0 start script.
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    |
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | npm ERR! A complete log of this run can be found in:
captain-captain.1.vi28zhwpz7u2@captain-duck-duck-001    | npm ERR!     /root/.npm/_logs/2018-12-30T20_29_07_321Z-debug.log
```
These health-checks seem to be failing.

**Comment by githubsaturn** [comment]
Ahhh that explains it. Captain does perform automatic health checks to make sure it can access itself. If it fails too many times it restarts itself. 

You probably have some non standard condition on your server.
- What's your firewall settings?
- Do you have IPv6 enabled for your domain?
- Is you server on a local network that's being blocked behind a NAT?
- Who are you using as server provider?
- Did you have any problem when installing Captain on your server? Did you have to use `BY_PASS_PROXY_CHECK`?

**Comment by roelvan** [comment]
I think I found it, I ran: `ufw enable` so now the health-checks are failing. Is it secure to do `ufw disable`? Or should I only open the ports mentioned in the Captain docs?
Thank you so much for your help!

**Comment by githubsaturn** [comment]
It's better to have only the required ports open. Make sure to have your ssh port open as well. Otherwise you'll be locked out of the server.
