### ISSUE TITLE
Cannot read property 'stop' of undefined

### ISSUE THREAD

**Issue by dottodot** [githubsaturn/captainduckduck#39]
When I deploy I've suddenly started getting this error

```
/usr/local/lib/node_modules/captainduckduck/captainduckduck-deploy.js:243
        spinner.stop();
                ^

TypeError: Cannot read property 'stop' of undefined
    at Request.callback [as _callback] (/usr/local/lib/node_modules/captainduckduck/captainduckduck-deploy.js:243:17)
    at Request.self.callback (/usr/local/lib/node_modules/captainduckduck/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/captainduckduck/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/captainduckduck/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
```

**Comment by githubsaturn** [comment]
Do you have a repro case for this? Does this happen if you try to deploy the sample apps as well?

**Comment by dottodot** [comment]
Actually think the issue was on the server as just gone to setup an app to test the example node app to find I can't access the dashboard (see attached screenshot)

But once I ssh'd into my server there seemed to be a container that not properly deployed and removing that allowed the dashboard to load and my original error also seems to have resolved itself.

![captain duck dottodotdesign co uk_](https://user-images.githubusercontent.com/811652/34004938-4ec289ae-e0f1-11e7-9322-319580668e73.png)

**Comment by githubsaturn** [comment]
Having a problemistic container shouldn't affect functionality of Captain (you should still be able to access the dashboard). If you have a repro case for it, or you find more details, please let me know .

**Comment by dottodot** [comment]
Yeah I'm not entirely sure what the cause was, it could have also been a disk space issue as I'd also maxed that out. Anyway I'll close for now until I have any more meaningful information.
