### ISSUE TITLE
Installing locally

### ISSUE THREAD

**Issue by saihegde** [githubsaturn/captainduckduck#57]
Issues installing locally even after following the dnsq steps

```
Captain Starting ...
Installing Captain Service ...
December 18th 2017, 11:51:11.295 pm    Starting swarm at 34.232.18.13:2377
Installation failed.
{ Error: (HTTP code 400) bad parameter - must specify a listening address because the address to advertise is not recognized as a system address, and a system's IP address to use could not be uniquely identified
    at /usr/src/app/node_modules/docker-modem/lib/modem.js:254:17
    at getCause (/usr/src/app/node_modules/docker-modem/lib/modem.js:284:7)
    at Modem.buildPayload (/usr/src/app/node_modules/docker-modem/lib/modem.js:253:5)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:229:14)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1057:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  reason: 'bad parameter',
  statusCode: 400,
  json:
   { message: 'must specify a listening address because the address to advertise is not recognized as a system address, and a system\'s IP address to use could not be uniquely identified' } }
```

Output of nslookup a.captain.x

```
Server:         127.0.0.1
Address:        127.0.0.1#53

Name:   a.captain.x
Address: 127.0.0.1
```

**Comment by githubsaturn** [comment]
What's your environment? Linux, Mac, Windows or VM?

**Comment by saihegde** [comment]
Ubuntu 17.04

**Comment by githubsaturn** [comment]
It's weird. I just tried it on a brand new ubuntu behind a router and everything worked. Anyways, try this:
```
docker run -e "MAIN_NODE_IP_ADDRESS=192.168.1.2" -v /var/run/docker.sock:/var/run/docker.sock dockersaturn/captainduckduck
```

and replace `192.168.1.2` with your own local IP.

**Comment by saihegde** [comment]
Awesome.... that worked. Thanks.

**Comment by githubsaturn** [comment]
<p>
    <img alt="CaptainDuckDuck" src="https://media3.giphy.com/media/NeKB8ZR67TuV2/giphy.gif" width="450"/>
</p>

**Comment by kristijanPetr** [comment]
Is it possible to run on a local network, then expose it to public url and add domain to it?

**Comment by githubsaturn** [comment]
See this: https://caprover.com/docs/run-locally.html

Yes. It's technically possible, but it's not very straightforward.
