### ISSUE TITLE
"Captain is not ready yet"

### ISSUE THREAD

**Issue by icebob** [githubsaturn/captainduckduck#6]
Hi,

great project! I want to trying. I installed it with `mkdir /captain && docker run -v /var/run/docker.sock:/var/run/docker.sock dockersaturn/captainduckduck` on RancherOS, It started, but I always got the "Captain is not ready yet" message on UI login screen. The docker logs says:

```
October 28th 2017, 12:35:18.784 pm    Emptying generated and temp folders.
October 28th 2017, 12:35:18.800 pm    Ensuring directories are available on host. Started.
October 28th 2017, 12:35:18.809 pm    Ensuring directories are available on host. Finished.
October 28th 2017, 12:35:18.815 pm    Attaching network captain-overlay-network to service: captain-captain
October 28th 2017, 12:35:18.829 pm    Error: (HTTP code 500) server error - rpc error: code = 2 desc = changing network in service is not supported
Error: (HTTP code 500) server error - rpc error: code = 2 desc = changing network in service is not supported
    at /usr/src/app/node_modules/docker-modem/lib/modem.js:254:17
    at getCause (/usr/src/app/node_modules/docker-modem/lib/modem.js:284:7)
    at Modem.buildPayload (/usr/src/app/node_modules/docker-modem/lib/modem.js:253:5)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:229:14)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1057:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
POST /api/v1/login 200 30.097 ms - 59
```

What is the problem?

**Comment by icebob** [comment]
Sorry, I tried on an old Docker (1.13). I updated to 17.06 and it's working.
